import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import { twMerge as cn } from "tailwind-merge";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { AppContext } from "@/components/context/app-context";
import { useContext, useState } from "react";
import { AppWrapper } from "@/components/app-wrapper";

// const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({
    subsets: ["latin"],
    weight: "400",
    variable: "--font-roboto"
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn("font-roboto text-default-950", roboto.className)}
            >
                <AppWrapper>{children}</AppWrapper>
            </body>
        </html>
    );
}
